config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  devise_for :models
  root to: 'home#index'
  resources :categories, except: [:show]
  resources :clients, except: [:show]
  resources :suppliers, except: [:show]
  resources :products, except: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/client.rb
class Client < ApplicationRecord
  has_many :sales
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :supplier
  has_many :warehouse_records

  mount_uploader :imagen, ImagenProductoUploader
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :Client
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products
  has_many :warehouse_record
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/warehouse_record.rb
class WarehouseRecord < ApplicationRecord
  belongs_to :supplier
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller?
      "devise"
    else
      "application"
    end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:edit, :update, :destroy]

  def index
    @categorias = Category.all
  end

  def new
    @categoria = Category.new
  end

  def edit
  end

  def create
    @categoria = Category.new(category_params)

    respond_to do |format|
      if @categoria.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @categoria.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @categoria.update(category_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @categoria.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @categoria.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private
  def set_category
    @categoria = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:nombre, :descripcion)
  end
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_Client, only: [:edit, :update, :destroy]

  def index
    @clientes = Client.all
  end

  def new
    @cliente = Client.new
  end

  def edit
  end

  def create
    @cliente = Client.new(client_params)

    respond_to do |format|
      if @cliente.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @cliente.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @cliente.update(client_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @cliente.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @cliente.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private
  def set_Client
    @cliente = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:nombre, :direccion, :telefono)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index 
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]
  before_action :set_categories, only: [:new, :edit]
  before_action :set_suppliers, only: [:new, :edit]

  def index
    @productos = Product.all
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.json {head :no_content}
        format.js
      else
        format.json { render json: @product.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @product.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private
  def product_params
    params.require(:product).permit(:imagen, :nombre, :descripcion, :existencia, :precio, :category_id, :supplier_id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def set_categories
    @categorias = Category.all
  end

  def set_suppliers
    @proveedores = Supplier.all
  end
  
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_Supplier, only: [:edit, :update, :destroy]

  def index
    @proveedores = Supplier.all
  end

  def new
    @proveedor = Supplier.new
  end

  def edit
  end

  def create
    @proveedor = Supplier.new(supplier_params)

    respond_to do |format|
      if @proveedor.save
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @proveedor.errors.full_messages, status: :unprocessable_entity }
        format.js { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @proveedor.update(supplier_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @proveedor.errors.full_messages, status: :unprocessable_entity }
        format.js { render :edit }
      end
    end
  end

  def destroy
    @proveedor.destroy
    respond_to do |format|
      format.json { head :no_content }
      format.js
    end
  end

  private
  def set_Supplier
    @proveedor = Supplier.find(params[:id])
  end

  def supplier_params
    params.require(:supplier).permit(:nombre, :direccion, :telefono)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/categories/_form.html.erb
<%= form_for @categoria, remote: true do |f| %>
  <div class="form-group">
    <h4 class="control-label">Datos de la categoría:</h4>
  </div>

  <div class="item form-group<%= @categoria.errors[:nombre].any? ? ' has-error has-feedback ' : '' %>">
    <%= f.label :nombre, "Nombre de Categoría: " %>
    <div class="input-group">
      <%= f.text_field :nombre, {:class=> "form-control first_input", :placeholder=>"Introduzca el nombre de la categoría..."} %>
      <% if @categoria.errors[:nombre].any? %>
        <p class="bg-danger"><%= @categoria.errors[:nombre].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @categoria.errors[:descripcion].any? ? ' has-error has-feedback ' : '' %>">
    <%= f.label :descripcion, "Descripción de la Categoría: " %>
    <div class="input-group">
      <%= f.text_area :descripcion, {:class=> "form-control", :placeholder=>"Introduzca el descripción de la categoría..."} %>
      <% if @categoria.errors[:descripcion].any? %>
        <p class="bg-danger"><%= @categoria.errors[:descripcion].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
    <%= f.submit @categoria.new_record? ? "Crear Categoría" : "Actualizar Categoría", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/categories/_modal_categorias.html.erb
<!-- MODAL -->
<div class="modal fade" id="modalCategorias" tabindex="-1" role="dialog" aria-labelledby="modalCategorias">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-categorias-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-categorias modal-body" id="modal-body-categorias">

      </div>
      <div class="modal-footer" id="modal-footer-categorias">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
<!-- FIN MODAL -->

app/views/categories/create.js.erb
$('#modalCategorias').modal('toggle');
$('#tablaCategorias').append('<tr id="categoria_<%= @categoria.id %>" ><td><%= @categoria.nombre %></td><td><%= @categoria.descripcion %></td><td><%= link_to 'Editar', edit_category_path(@categoria), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to 'Borrar', @categoria, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{@categoria.nombre}?" }, class: "btn btn-danger btn-xs" %></td></tr>');

app/views/categories/destroy.js.erb
$('#categoria_<%= @categoria.id %>').fadeOut();

app/views/categories/edit.js.erb
// Add the dialog title
$('#modal-categorias-title').html("Editar categoría");

// Render the new form
$('.modal-body-categorias').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#modalCategorias').modal("show");

// Set focus to the first element
$('#modalCategorias').on('shown.bs.modal', function () {
  $('.first_input').focus();
});

app/views/categories/index.html.erb
<h1 class="h3 mb-2 text-gray-800">Categorías de productos</h1>

<div>
  <%= link_to new_category_path, { remote: true, class: "btn btn-info", id: "anadir-categoria-btn" } do %>
    <span class="fas fa-plus-square"></span>
    <% end %>
</div>
<br>

<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table id="tablaCategorias" class="table table-bordered" width="100%">
        <thead>
          <th>Nombre Categoría</th>
          <th>Descripción</th>
          <th>Acciones</th>
        </thead>
        <tbody>
          <% @categorias.each do |cat| %>
            <tr id="categoria_<%= cat.id %>">
              <td><%= cat.nombre %></td>
              <td><%= cat.descripcion %></td>
              <td>
                <%= link_to "Editar", edit_category_path(cat), html_options = {class: "btn btn-info btn-xs", remote: true } %>
                <%= link_to "Borrar", cat, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{cat.nombre}?"}, class: "btn btn-danger btn-xs" %>
              </td>            
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'modal_categorias' %>

app/views/categories/new.js.erb
// Add the dialog title
$('#modal-categorias-title').html("Nueva categoría");

// Render the new form
$('.modal-body-categorias').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#modalCategorias').modal("show");

// Set focus to the first element
$('#modalCategorias').on('shown.bs.modal', function () {
  $('.first_input').focus();
});

app/views/categories/update.js.erb
$('#modalCategorias').modal('toggle');
$('#categoria_<%= @categoria.id %>').replaceWith('<tr id="categoria_<%= @categoria.id %>" ><td><%= @categoria.nombre %></td><td><%= @categoria.descripcion %></td><td><%= link_to 'Editar', edit_category_path(@categoria), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to 'Borrar', @categoria, remote: true, method: :delete, data: { confirm: "¿Borrar categoria: #{@categoria.nombre}?" }, class: "btn btn-danger btn-xs" %></td></tr>');

app/views/clients/_form.html.erb
<%= form_for @cliente, remote: true do |f| %>
  <div class="form-group">
    <h4 class="control-label">Datos del cliente:</h4>
  </div>

  <div class="item form-group<%= @cliente.errors[:nombre].any? ? ' has-error has-feedback ' : '' %>">
    <%= f.label :nombre, "Nombre del Cliente: " %>
    <div class="input-group">
      <%= f.text_field :nombre, {:class=> "form-control first_input", :placeholder=>"Introduzca el nombre del cliente..."} %>
      <% if @cliente.errors[:nombre].any? %>
        <p class="bg-danger"><%= @cliente.errors[:nombre].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @cliente.errors[:direccion].any? ? ' has-error has-feedback ' : '' %>">
    <%= f.label :direccion, "Dirección del Cliente: " %>
    <div class="input-group">
      <%= f.text_area :direccion, {:class=> "form-control", :placeholder=>"Introduzca el dirección del cliente..."} %>
      <% if @cliente.errors[:direccion].any? %>
        <p class="bg-danger"><%= @cliente.errors[:direccion].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="item form-group<%= @cliente.errors[:telefono].any? ? ' has-error has-feedback ' : '' %>">
    <%= f.label :telefono, "Teléfono del Cliente: " %>
    <div class="input-group">
      <%= f.text_field :telefono, {:class=> "form-control", :placeholder=>"Introduzca el Teléfono del cliente..."} %>
      <% if @cliente.errors[:telefono].any? %>
        <p class="bg-danger"><%= @cliente.errors[:telefono].to_s[/\w([^"]*)/] %></p>
      <% end %>
    </div>
  </div>

  <div class="actions col-md-9 col-sm-9 col-xs-12 col-md-offset-3">
    <%= f.submit @cliente.new_record? ? "Crear Cliente" : "Actualizar Cliente", :class => "btn btn-success" %>
  </div>
<% end %>

app/views/clients/_modal_clientes.html.erb
<!-- MODAL -->
<div class="modal fade" id="modalClientes" tabindex="-1" role="dialog" aria-labelledby="modalClientes">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-clientes-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-clientes modal-body" id="modal-body-clientes">

      </div>
      <div class="modal-footer" id="modal-footer-clientes">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
<!-- FIN MODAL -->

app/views/clients/create.js.erb
$('#modalClientes').modal('toggle');
$('#tablaClientes').append('<tr id="cliente_<%= @cliente.id %>" ><td><%= @cliente.nombre %></td><td><%= @cliente.direccion %></td><td><%= @cliente.telefono %></td><td><%= link_to 'Editar', edit_client_path(@cliente), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to 'Borrar', @cliente, remote: true, method: :delete, data: { confirm: "¿Borrar cliente: #{@cliente.nombre}?" }, class: "btn btn-danger btn-xs" %></td></tr>');

app/views/clients/destroy.js.erb
$('#cliente_<%= @cliente.id %>').fadeOut();

app/views/clients/edit.js.erb
// Add the dialog title
$('#modal-clientes-title').html("Editar cliente");

// Render the new form
$('.modal-body-clientes').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#modalClientes').modal("show");

// Set focus to the first element
$('#modalClientes').on('shown.bs.modal', function () {
  $('.first_input').focus();
});

app/views/clients/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Clientes</h1>
<!-- DataTables Example -->
<div>
  <%= link_to new_client_path, {remote: true, class: "btn btn-info", id: "anadir-cliente-btn" } do %>
    <span class="fas fa-plus-square"></span>
  <% end %>
</div>
<br>
<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="tablaClientes" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Teléfono</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @clientes.each do |clie| %>
            <tr id="cliente_<%= clie.id %>">
              <td><%= clie.nombre %></td>
              <td><%= clie.direccion %></td>
              <td><%= clie.telefono %></td>
              <td>
                <%= link_to "Editar", edit_client_path(clie), html_options = {class: "btn btn-info btn-xs", remote: true } %>
                <%= link_to "Borrar", clie, remote: true, method: :delete, data: { confirm: "¿Borrar cliente: #{clie.nombre}?"}, class: "btn btn-danger btn-xs" %>
              </td>            
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'modal_clientes' %>

app/views/clients/new.js.erb
// Add the dialog title
$('#modal-clientes-title').html("Nuevo cliente");

// Render the new form
$('.modal-body-clientes').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#modalClientes').modal("show");

// Set focus to the first element
$('#modalClientes').on('shown.bs.modal', function () {
  $('.first_input').focus();
});

app/views/clients/update.js.erb
$('#modalClientes').modal('toggle');
$('#cliente_<%= @cliente.id %>').replaceWith('<tr id="cliente_<%= @cliente.id %>" ><td><%= @cliente.nombre %></td><td><%= @cliente.direccion %></td><td><%= @cliente.telefono %></td><td><%= link_to 'Editar', edit_client_path(@cliente), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to 'Borrar', @cliente, remote: true, method: :delete, data: { confirm: "¿Borrar cliente: #{@cliente.nombre}?" }, class: "btn btn-danger btn-xs" %></td></tr>');

app/views/home/index.html.erb
<h1>Home#index</h1>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="es">

<head>
  <title>AppComercial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "sb-admin-2.min" %>

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-10 col-lg-12 col-md-9">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
              <div class="col-lg-6">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                  </div>
                    <%= yield %>
                    
                  <hr>
                
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

</body>

</html>

app/views/products/_modal_productos.html.erb
<!-- MODAL -->
<div class="modal fade" id="modalProductos" tabindex="-1" role="dialog" aria-labelledby="modalProductos">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-productos-title">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body-productos modal-body" id="modal-body-productos">

      </div>
      <div class="modal-footer" id="modal-footer-productos">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>
<!-- FIN MODAL -->

app/views/products/create.js.erb
$('#modalProductos').modal('toggle');
$('#tablaProductos').append('<tr id="producto_<%= @product.id %>" ><td><%= image_tag(@product.imagen.url, size: "50x50", class: "rounded-circle") if @product.imagen? %></td><td><%= @product.nombre %></td><td><%= @product.existencia %></td><td><%= @product.precio %></td><td><%= @product.category !=nil ? @product.category.nombre : "No tiene categoría" %></td><td><%= @product.supplier !=nil ? @product.supplier.nombre : "No tiene proveedor" %></td><td><%= link_to 'Editar', edit_product_path(@product), html_options = {class: "btn btn-info btn-xs", remote: true} %><%= link_to 'Borrar', @product, remote: true, method: :delete, data: { confirm: "¿Borrar producto: #{@product.nombre}?" }, class: "btn btn-danger btn-xs" %></td></tr>');

app/views/products/destroy.js.erb
$('#producto_<%= @product.id %>').fadeOut();

app/views/products/edit.js.erb
// Add the dialog title
$('#modal-productos-title').html("Editar producto");

// Render the new form
$('.modal-body-productos').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#modalProductos').modal("show");

// Set focus to the first element
$('#modalProductos').on('shown.bs.modal', function () {
  $('.first_input').focus();
});

app/views/products/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Productos</h1>
<!-- DataTables Example -->
<div>
  <%= link_to new_product_path, {remote: true, class: "btn btn-info" } do %>
    <span class="fas fa-plus-square"></span>
  <% end %>
</div>
<br>
<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="tablaProductos" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Imagen</th>
            <th>Nombre</th>
            <th>Existencia</th>
            <th>Precio</th>
            <th>Categoria</th>
            <th>Proveedor</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @productos.each do |prod| %>
            <tr id="producto_<%= prod.id %>">
              <td><%= image_tag(prod.imagen.url, size: "50x50", class: "rounded-circle") if prod.imagen? %></td>
              <td><%= prod.nombre %></td>
              <td><%= prod.existencia %></td>
              <td><%= prod.precio %></td>
              <td><%= prod.category !=nil ? prod.category.nombre : "No tiene categoría" %></td>
              <td><%= prod.supplier !=nil ? prod.supplier.nombre : "No tiene proveedor" %></td>
              <td>
                <%= link_to "Editar", edit_product_path(prod), html_options = {class: "btn btn-info btn-xs", remote: true } %>
                <%= link_to "Borrar", prod, remote: true, method: :delete, data: { confirm: "¿Borrar producto: #{prod.nombre}?"}, class: "btn btn-danger btn-xs" %>
              </td>            
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'modal_productos' %>

app/views/products/new.js.erb
// Add the dialog title
$('#modal-productos-title').html("Nuevo Producto");

// Render the new form
$('.modal-body-productos').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#modalProductos').modal("show");

// Set focus to the first element
$('#modalProductos').on('shown.bs.modal', function () {
  $('.first_input').focus();
});

app/views/products/update.js.erb
$('#modalProductos').modal('toggle');
$('#producto_<%= @product.id %>').replaceWith('<tr id="producto_<%= @product.id %>" ><td><%= image_tag(@product.imagen.url, size: "50x50", class: "rounded-circle") if @product.imagen? %></td><td><%= @product.nombre %></td><td><%= @product.existencia %></td><td><%= @product.precio %></td><td><%= @product.category !=nil ? @product.category.nombre : "No tiene categoría" %></td><td><%= @product.supplier !=nil ? @product.supplier.nombre : "No tiene proveedor" %></td><td><%= link_to 'Editar', edit_product_path(@product), html_options = {class: "btn btn-info btn-xs", remote: true} %><%= link_to 'Borrar', @product, remote: true, method: :delete, data: { confirm: "¿Borrar producto: #{@product.nombre}?" }, class: "btn btn-danger btn-xs" %></td></tr>');

app/views/suppliers/create.js.erb
$('#modalProveedores').modal('toggle');
$('#tablaProveedores').append('<tr id="proveedor_<%= @proveedor.id %>" ><td><%= @proveedor.nombre %></td><td><%= @proveedor.direccion %></td><td><%= @proveedor.telefono %></td><td><%= link_to 'Editar', edit_supplier_path(@proveedor), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to 'Borrar', @proveedor, remote: true, method: :delete, data: { confirm: "¿Borrar proveedor: #{@proveedor.nombre}?" }, class: "btn btn-danger btn-xs" %></td></tr>');

app/views/suppliers/destroy.js.erb
$('#proveedor_<%= @proveedor.id %>').fadeOut();

app/views/suppliers/index.html.erb
<!-- Page Heading -->
<h1 class="h3 mb-2 text-gray-800">Proveedores</h1>
<!-- DataTables Example -->
<div>
  <%= link_to new_supplier_path, {remote: true, class: "btn btn-info", id: "anadir-proveedor-btn" } do %>
    <span class="fas fa-plus-square"></span>
  <% end %>
</div>
<br>
<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="tablaProveedores" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Teléfono</th>
            <th>Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% @proveedores.each do |prov| %>
            <tr id="proveedor_<%= prov.id %>">
              <td><%= prov.nombre %></td>
              <td><%= prov.direccion %></td>
              <td><%= prov.telefono %></td>
              <td>
                <%= link_to "Editar", edit_supplier_path(prov), html_options = {class: "btn btn-info btn-xs", remote: true } %>
                <%= link_to "Borrar", prov, remote: true, method: :delete, data: { confirm: "¿Borrar proveedor: #{prov.nombre}?"}, class: "btn btn-danger btn-xs" %>
              </td>            
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'modal_proveedores' %>

app/views/suppliers/update.js.erb
$('#modalProveedores').modal('toggle');
$('#proveedor_<%= @proveedor.id %>').replaceWith('<tr id="proveedor_<%= @proveedor.id %>" ><td><%= @proveedor.nombre %></td><td><%= @proveedor.direccion %></td><td><%= @proveedor.telefono %></td><td><%= link_to 'Editar', edit_supplier_path(@proveedor), html_options = {class: "btn btn-info btn-xs", remote: true} %> <%= link_to 'Borrar', @proveedor, remote: true, method: :delete, data: { confirm: "¿Borrar proveedor: #{@proveedor.nombre}?" }, class: "btn btn-danger btn-xs" %></td></tr>');